tests:
  sgGrp:
    template_file: s3-template.json
    region: us-east-2
notify: 
  - abc.xyz.com
account_details:
  accountId: 111111111111
  cross_account_role: arn:aws:iam::111111111111:role/AWSCloudFormationStackSetExecutionRole